services:
  speedtest:
    container_name: openspeedtest
    image: openspeedtest/latest
    restart: unless-stopped
    volumes:
      - appdata:/appdata
    env_file:
      - .env
    # Uncomment to expose speedtest on ports 3000 http and 3001 https
    # ports:
    #   - '3000:3000'
    #   - '3001:3001'
    networks:
      - proxiable

volumes:
  appdata:

networks:
  proxiable:
    external: true
